import { getAdoClient } from "./client.js";
import { config } from "../config/index.js";
import { agentLogger } from "../utils/logger.js";
import { bugAlreadyFiled, addMemory } from "../memory/store.js";

const log = agentLogger("ADO:Bug");

export interface BugReport {
  title: string;
  description: string;
  stepsToReproduce: string;
  expectedResult: string;
  actualResult: string;
  errorLogs: string;
  screenshotPath?: string;
  testCaseRef: string;
  rcaSummary: string;
  rootCause: string;
  severity: "1 - Critical" | "2 - High" | "3 - Medium" | "4 - Low";
  parentStoryId: number;
}

export interface CreatedBug {
  id: number;
  url: string;
}

/**
 * Search existing bugs to prevent duplicates.
 */
async function findDuplicateBug(
  title: string,
  storyId: number
): Promise<number | null> {
  const client = getAdoClient();
  const wiql = `
    SELECT [System.Id]
    FROM WorkItems
    WHERE [System.WorkItemType] = 'Bug'
      AND [System.State] <> 'Closed'
      AND [System.Title] CONTAINS '${title.replace(/'/g, "''").slice(0, 100)}'
      AND [System.Parent] = ${storyId}
  `;

  try {
    const result = await client.post(
      "/wit/wiql",
      { query: wiql },
      { headers: { "Content-Type": "application/json" } }
    );
    if (result.data.workItems?.length > 0) {
      return result.data.workItems[0].id;
    }
  } catch {
    log.warn("Duplicate search failed, proceeding with creation");
  }
  return null;
}

/**
 * Create a bug in Azure DevOps and link it to the parent story.
 */
export async function createBug(report: BugReport): Promise<CreatedBug | null> {
  // Check local memory first
  if (bugAlreadyFiled(report.testCaseRef, report.rootCause)) {
    log.warn(`Bug already filed for test="${report.testCaseRef}" cause="${report.rootCause}". Skipping.`);
    return null;
  }

  // Check ADO for duplicates
  const existingId = await findDuplicateBug(report.title, report.parentStoryId);
  if (existingId) {
    log.warn(`Duplicate bug found in ADO: #${existingId}. Skipping creation.`);
    return null;
  }

  const client = getAdoClient();

  const body = [
    { op: "add", path: "/fields/System.Title", value: report.title },
    {
      op: "add",
      path: "/fields/System.Description",
      value: formatBugDescription(report),
    },
    {
      op: "add",
      path: "/fields/Microsoft.VSTS.TCM.ReproSteps",
      value: report.stepsToReproduce,
    },
    {
      op: "add",
      path: "/fields/Microsoft.VSTS.Common.Severity",
      value: report.severity,
    },
    {
      op: "add",
      path: "/fields/System.Tags",
      value: "auto-qa-agent;rca-generated",
    },
    // Link to parent story
    {
      op: "add",
      path: "/relations/-",
      value: {
        rel: "System.LinkTypes.Hierarchy-Reverse",
        url: `${config.ado.apiBase}/wit/workitems/${report.parentStoryId}`,
      },
    },
  ];

  log.info(`Creating bug: "${report.title}"`);
  const response = await client.post("/wit/workitems/$Bug", body);

  const createdBug: CreatedBug = {
    id: response.data.id,
    url: response.data._links?.html?.href ?? "",
  };

  // Record in memory
  addMemory({
    type: "bug_filed",
    storyId: String(report.parentStoryId),
    testName: report.testCaseRef,
    data: {
      bugId: createdBug.id,
      rootCause: report.rootCause,
      title: report.title,
    },
  });

  log.info(`Bug created: #${createdBug.id} → ${createdBug.url}`);
  return createdBug;
}

function formatBugDescription(report: BugReport): string {
  return `
<h2>Bug Report (Auto-generated by QA Agent)</h2>

<h3>Description</h3>
<p>${report.description}</p>

<h3>Steps to Reproduce</h3>
<pre>${report.stepsToReproduce}</pre>

<h3>Expected Result</h3>
<p>${report.expectedResult}</p>

<h3>Actual Result</h3>
<p>${report.actualResult}</p>

<h3>RCA Summary</h3>
<p>${report.rcaSummary}</p>

<h3>Error Logs</h3>
<pre>${report.errorLogs.slice(0, 2000)}</pre>

<h3>Test Case Reference</h3>
<p>${report.testCaseRef}</p>
`.trim();
}
